class_name CombatAudio
extends Node3D

## CombatAudio — Audio hook manager providing 3D spatial sound triggers for all melee combat events.
## Uses in-memory procedural waveforms generated by SFXGenerator for zero-overhead sound.

const SFXGen = preload("res://scripts/audio/sfx_generator.gd")

static var _stream_swing: AudioStreamWAV = null
static var _stream_impact_light: AudioStreamWAV = null
static var _stream_impact_heavy: AudioStreamWAV = null
static var _stream_parry: AudioStreamWAV = null
static var _stream_block: AudioStreamWAV = null
static var _stream_dodge: AudioStreamWAV = null
static var _stream_death: AudioStreamWAV = null
static var _stream_ult_activation: AudioStreamWAV = null
static var _stream_ult_buildup: AudioStreamWAV = null
static var _stream_ult_sword_rise: AudioStreamWAV = null
static var _stream_ult_climax: AudioStreamWAV = null
static var _stream_ult_dissolution: AudioStreamWAV = null
static var _stream_ult_victory: AudioStreamWAV = null

@onready var sfx_player: AudioStreamPlayer3D = AudioStreamPlayer3D.new()

func _ready() -> void:
	add_child(sfx_player)
	sfx_player.max_distance = 30.0
	sfx_player.unit_size = 4.0

	_ensure_streams()

static func _ensure_streams() -> void:
	if not _stream_swing:
		_stream_swing = SFXGen.generate_sword_swing()
	if not _stream_impact_light:
		_stream_impact_light = SFXGen.generate_weapon_impact(false)
	if not _stream_impact_heavy:
		_stream_impact_heavy = SFXGen.generate_weapon_impact(true)
	if not _stream_parry:
		_stream_parry = SFXGen.generate_parry_ring()
	if not _stream_block:
		_stream_block = SFXGen.generate_shield_block()
	if not _stream_dodge:
		_stream_dodge = SFXGen.generate_dodge_whoosh()
	if not _stream_death:
		_stream_death = SFXGen.generate_death_collapse()
	if not _stream_ult_activation:
		_stream_ult_activation = SFXGen.generate_ultimate_activation()
	if not _stream_ult_buildup:
		_stream_ult_buildup = SFXGen.generate_ultimate_buildup()
	if not _stream_ult_sword_rise:
		_stream_ult_sword_rise = SFXGen.generate_ultimate_sword_rise()
	if not _stream_ult_climax:
		_stream_ult_climax = SFXGen.generate_ultimate_climax()
	if not _stream_ult_dissolution:
		_stream_ult_dissolution = SFXGen.generate_ultimate_dissolution()
	if not _stream_ult_victory:
		_stream_ult_victory = SFXGen.generate_ultimate_victory()

func play_sword_swing() -> void:
	_play_stream(_stream_swing, 0.95 + randf() * 0.1)

func play_weapon_impact(is_heavy: bool = false) -> void:
	var stream: AudioStreamWAV = _stream_impact_heavy if is_heavy else _stream_impact_light
	_play_stream(stream, 0.92 + randf() * 0.15)

func play_block() -> void:
	_play_stream(_stream_block, 0.95 + randf() * 0.1)

func play_shield_block() -> void:
	play_block()

func play_flesh_hit() -> void:
	play_weapon_impact(false)

func play_armor_hit() -> void:
	play_weapon_impact(true)

func play_parry() -> void:
	_play_stream(_stream_parry, 1.0 + (randf() * 0.1 - 0.05))

func play_dodge() -> void:
	_play_stream(_stream_dodge, 1.0 + randf() * 0.1)

func play_death() -> void:
	_play_stream(_stream_death, 0.9)

func play_ability_cast(_ability_name: String) -> void:
	_play_stream(_stream_impact_heavy, 1.2)

func play_ultimate_activation() -> void:
	_play_stream(_stream_ult_activation, 1.0)

func play_ultimate_buildup() -> void:
	_play_stream(_stream_ult_buildup, 1.0)

func play_ultimate_sword_rise() -> void:
	_play_stream(_stream_ult_sword_rise, 1.0)

func play_ultimate_climax() -> void:
	_play_stream(_stream_ult_climax, 1.0)

func play_ultimate_dissolution() -> void:
	_play_stream(_stream_ult_dissolution, 1.0)

func play_ultimate_victory() -> void:
	_play_stream(_stream_ult_victory, 1.0)

func _play_stream(stream: AudioStream, pitch_scale: float = 1.0) -> void:
	if not stream: return
	sfx_player.stream = stream
	sfx_player.pitch_scale = pitch_scale
	sfx_player.play()
